nav:
  - Lamp of Malice Guide: './lamp-of-malice/lamp-of-malice-text-guide.md'
  - Old Castle Ruins Guide:
    - Season 1: './old-castle-ruins/season-1/old-castle-ruins-season-1.md'
    - Season 2: './old-castle-ruins/season-2/old-castle-ruins-season-2.md'
  - Labyrinth of Fordraig Guide: './labyrinth-of-fordraig/labyrinth-of-fordraig-guide.md'
  - Pixie and the Secret Garden Guide: './pixie-and-the-secret-garden/pixie-and-the-secret-garden-guide.md'
  - Otherworld Adventurers Guide: './otherworld-adventurers/otherworld-adventurers-guide.md'
  - Fighter Proving Grounds Guide: './fighter-proving-grounds/fighter-proving-grounds-guide.md'
  - Mage Proving Grounds Guide: './mage-proving-grounds/mage-proving-grounds-guide.md'
  - Plot of the Sand Shadow Guide: './plot-of-the-sand-shadow/plot-of-the-sand-shadow.md'
  - Recurring Events Guide: './recurring-events/recurring-events.md'
