nav:
  - Dungeons: 
    - Ancient Mausoleum: './abyss-guides/ancient-mausoleum/maps.md'
    - Dens: 
      - Den of Earth: './abyss-guides/dens/den-of-earth.md'
      - Den of Fire: './abyss-guides/dens/den-of-fire.md'
      - Den of Wind: './abyss-guides/dens/den-of-wind.md'
      - Den of Light: './abyss-guides/dens/den-of-light.md'
      - Den of Water: './abyss-guides/dens/den-of-water.md'
  - Special Events: 
    - Lamp of Malice: './lamp-of-malice/lamp-of-malice-text-guide.md'
    - Labyrinth of Fordraig: './labyrinth-of-fordraig/labyrinth-of-fordraig-guide.md'
    - Pixie and the Secret Garden: './pixie-and-the-secret-garden/pixie-and-the-secret-garden-guide.md'
    - Otherworld Adventurers: './otherworld-adventurers/otherworld-adventurers-guide.md'
    - Plot of the Sand Shadow: './plot-of-the-sand-shadow/plot-of-the-sand-shadow.md'
    - Alabaster Hunting: './alabaster-hunting/alabaster-hunting.md'
    - Recurring Events: './recurring-events/recurring-events.md'
  - Request from an Ally:
    - Symbol of Alliance: './abyss-guides/request-from-an-ally/symbol-of-alliance.md'
    - Arna's Past: './abyss-guides/request-from-an-ally/arnas-past.md'
    - Memories of Charlotte: './abyss-guides/request-from-an-ally/memories-of-charlotte.md'
  - Proving Grounds: 
    - Fighter Proving Grounds Guide: './fighter-proving-grounds/fighter-proving-grounds-guide.md'
    - Mage Proving Grounds Guide: './mage-proving-grounds/mage-proving-grounds-guide.md'
    - Knight Proving Grounds Guide: './knight-proving-grounds/knight-proving-grounds-guide.md'
  - Old Castle Ruins:
    - Season 1: './old-castle-ruins/season-1/old-castle-ruins-season-1.md'
    - Season 2: './old-castle-ruins/season-2/old-castle-ruins-season-2.md'
    - Season 3: './old-castle-ruins/season-3/old-castle-ruins-season-3.md'
