nav:
  - Alabaster Hunting: './alabaster-hunting/alabaster-hunting.md'
  - Labyrinth of Fordraig: './labyrinth-of-fordraig/labyrinth-of-fordraig-guide.md'
  - Lamp of Malice: './lamp-of-malice/lamp-of-malice-text-guide.md'
  - Old Castle Ruins:
    - Season 1: './old-castle-ruins/season-1/old-castle-ruins-season-1.md'
    - Season 2: './old-castle-ruins/season-2/old-castle-ruins-season-2.md'
    - Season 3: './old-castle-ruins/season-3/old-castle-ruins-season-3.md'
  - Otherworld Adventurers: './otherworld-adventurers/otherworld-adventurers-guide.md'
  - Pixie and the Secret Garden: './pixie-and-the-secret-garden/pixie-and-the-secret-garden-guide.md'
  - Plot of the Sand Shadow: './plot-of-the-sand-shadow/plot-of-the-sand-shadow.md'
  - Proving Grounds: 
    - Fighter Proving Grounds: './fighter-proving-grounds/fighter-proving-grounds-guide.md'
    - Mage Proving Grounds: './mage-proving-grounds/mage-proving-grounds-guide.md'
    - Knight Proving Grounds: './knight-proving-grounds/knight-proving-grounds-guide.md'
  - Recurring Requests: 
    - Adventurer Retrieval: './recurring-events/adv-retrieval.md'
    - Gold Ore Collection: './recurring-events/gold-ore.md'
  - Vendetta on the Island of the Wailing Oni: './vendetta-on-the-island-of-the-wailing-oni/vendetta-on-the-island-of-the-wailing-oni.md'
