nav:
  - Blacksmithing: 'blacksmithing.md'
  - Weapon Types: 'weapon-types.md'
  - Equipment Tables: 'equipment-tables.md'
  - Unique Equipment: 'unique-equipment.md'
  - Equipment Drop Rates: 'equipment-drop-rates.md'
