nav:
  - Introduction: './0-introduction/index.md'
  - "Abyss 1: Beginning Abyss - Royal Capital":
      - Maps: './1-beginning-abyss/maps.md'
      - Requests: './1-beginning-abyss/requests.md'
      - Important Request /<br>Greater Warped One: './1-beginning-abyss/important-request-gwo.md'
      - Wandering NPCs: './1-beginning-abyss/wandering-npcs.md'
      - Place of Awakening: './1-beginning-abyss/awakening-preview-dungeon.md'
  - "Abyss 2: Trade Waterways - Port Town":
      - Maps: './2-port-town-grand-legion/maps.md'
      - Requests: './2-port-town-grand-legion/requests.md'
      - Important Request /<br>Greater Warped One: './2-port-town-grand-legion/important-request-gwo.md'
      - Wandering NPCs: './2-port-town-grand-legion/wandering-npcs.md'
  - "Abyss 3: Impregnable Fortress - Guarda":
      - Maps: './3-guarda-fortress/maps.md'
      - Requests: './3-guarda-fortress/requests.md'
      - Important Request /<br>Greater Warped One: './3-guarda-fortress/important-request-gwo.md'
      - Corrosion Sentries: './3-guarda-fortress/corrosion.md'
      - Wandering NPCs: './3-guarda-fortress/wandering-npcs.md'
      - Misc Bosses:
          - Morgus, God of Death: './3-guarda-fortress/misc-bosses/morgus-god-of-death.md'
  - "Abyss 4: Deepsnow Hinterlands - Isberg":
      - Maps: './4-isberg/maps.md'
      - Requests: './4-isberg/requests.md'
      - Faction Requests: './4-isberg/faction-requests.md'
      - Important Request /<br>Greater Warped One: './4-isberg/important-request-gwo.md'
      - Wandering NPCs: './4-isberg/wandering-npcs.md'
  - Ancient Mausoleum: './ancient-mausoleum/maps.md'
  - Dens:
      - Den of Earth: './dens/den-of-earth.md'
      - Den of Fire: './dens/den-of-fire.md'
      - Den of Wind: './dens/den-of-wind.md'
      - Den of Light: './dens/den-of-light.md'
      - Den of Water: './dens/den-of-water.md'
  - Grade Exams: './grade-exams/maps.md'
  - Request from an Ally:
      - Symbol of Alliance: './request-from-an-ally/symbol-of-alliance.md'
      - Arna's Past: './request-from-an-ally/arnas-past.md'
      - Memories of Charlotte: './request-from-an-ally/memories-of-charlotte.md'
  - Bounties: './bounties/bounties.md'
