nav:
  - Achievements: './achievements.md'
  - Cursed Wheel Causality:
      - Beginning Abyss: './wheel-causality/beginning-abyss.md'
      - Port Town Grand Legion: './wheel-causality/port-town-grand-legion.md'
      - Guarda Fortress: './wheel-causality/guarda-fortress.md'
  - Dispatches: './dispatches.md'
  - Equipment:
      - Weapon Types: './equipment/weapon-types.md'
      - Unique Equipment: './equipment/unique-equipment.md'
      - Equipment Enhancement Tables: './equipment/equipment-tables.md'
  - Enemies: './enemy-compendium.md'
  - Harken's Blessings: './harkens-blessings.md'
  - Purchase Evaluation: './purchase-evaluation.md'
  - Purchaseable Skill Books: './purchaseable-skill-books.md'
  - Respawning Bone Locations: './respawning-bone-locations.md'
  - Skills and Spells: './skills-and-spells.md'
