nav:
  - Achievements: './achievements.md'
  - Cursed Wheel Causality:
      - Beginning Abyss: './wheel-causality/beginning-abyss.md'
      - Port Town Grand Legion: './wheel-causality/port-town-grand-legion.md'
      - Guarda Fortress: './wheel-causality/guarda-fortress.md'
      - Isberg: './wheel-causality/isberg.md'
      - Ally Requests: './wheel-causality/ally-requests.md'
  - Dispatches: './dispatches.md'
  - Economy:
      - Free-to-Play Resources: './free-to-play-economy.md'
      - Purchase Evaluation: './purchase-evaluation.md'
      - Purchaseable Skill Books: './purchaseable-skill-books.md'
  - Enemies: './enemy-compendium.md'
  - Grade Up: './grade-up/index.md'
  - Harken's Blessings: './harkens-blessings.md'
  - Skills And Spells:
      - Class Skill Quicklist: './skills-and-spells/class-skill-quicklist.md'
      - Full Skills and Spells List: './skills-and-spells/skills-and-spells.md'
