nav:
  - Achievements: './achievements.md'
  - Cursed Wheel Causality:
      - Beginning Abyss: './wheel-causality/beginning-abyss.md'
      - Port Town Grand Legion: './wheel-causality/port-town-grand-legion.md'
      - Guarda Fortress: './wheel-causality/guarda-fortress.md'
      - Ally Requests: './wheel-causality/ally-requests.md'
  - Dispatches: './dispatches.md'
  - Equipment:
      - Weapon Types: './equipment/weapon-types.md'
      - Unique Equipment: './equipment/unique-equipment.md'
  - Enemies: './enemy-compendium.md'
  - Harken's Blessings: './harkens-blessings.md'
  - Purchase Evaluation: './purchase-evaluation.md'
  - Purchaseable Skill Books: './purchaseable-skill-books.md'
  - Respawning Bone Locations: './respawning-bone-locations.md'
  - Skills And Spells:
      - Class Skill Quicklist: './skills-and-spells/class-skill-quicklist.md'
      - Inherit Skill Quicklist: './skills-and-spells/inherit-skill-quicklist.md'
      - Full Skills and Spells List: './skills-and-spells/skills-and-spells.md'