nav:
  - Adventurer Quicklist: './quicklist/adventurer-quicklist.md'
  - Legendary Adventurers:
    - Adventurer Review Criteria: './legendary-adventurers/details/_adventurer-review-criteria.md'
    - Abenius: './legendary-adventurers/details/Abenius.md'
    - Adam: './legendary-adventurers/details/Adam.md'
    - Ainikki: './legendary-adventurers/details/Ainikki.md'
    - Aldric: './legendary-adventurers/details/Aldric.md'
    - Alice: './legendary-adventurers/details/Alice.md'
    - Anemone: './legendary-adventurers/details/Anemone.md'
    - Arboris: './legendary-adventurers/details/Arboris.md'
    - Berkanan: './legendary-adventurers/details/Berkanan.md'
    - Debra: './legendary-adventurers/details/Debra.md'  
    - Erwin: './legendary-adventurers/details/Erwin.md'  
    - Galbadus: './legendary-adventurers/details/Galbadus.md'
    - Gerard: './legendary-adventurers/details/Gerard.md'
    - Gerulf: './legendary-adventurers/details/Gerulf.md'
    - Gillion: './legendary-adventurers/details/Gillion.md'
    - Iarumas: './legendary-adventurers/details/Iarumas.md'
    - Kagero: './legendary-adventurers/details/Kagero.md'
    - Lanavaille: './legendary-adventurers/details/Lanavaille.md'
    - Livana: './legendary-adventurers/details/Livana.md'
    - Linaria: './legendary-adventurers/details/Linaria.md'
    - Raffaello: './legendary-adventurers/details/Raffaello.md'
    - Red Beard: './legendary-adventurers/details/Red-Beard.md'
    - Rinne: './legendary-adventurers/details/Rinne.md'
    - Savia: './legendary-adventurers/details/Savia.md'
    - Shelirionach: './legendary-adventurers/details/Shelirionach.md'
    - Shiou: './legendary-adventurers/details/Shiou.md'
    - Yekaterina: './legendary-adventurers/details/Yekaterina.md'
    - Yoizou: './legendary-adventurers/details/Yoizou.md'
    - Yrsa: './legendary-adventurers/details/Yrsa.md'
    - Yuzunamiki: './legendary-adventurers/details/Yuzunamiki.md'
  - Legendary Requests:
    - Adam - Unnamed Request: './legendary-adventurers/legendary-requests/adam/adam-request.md'
    - Debra - Investigate the Island of Ghosts: './legendary-adventurers/legendary-requests/debra/debra-request.md'
    - Gerulf - Collect on a Broken Pact: './legendary-adventurers/legendary-requests/gerulf/gerulf-request.md'
    - Yekaterina - Unnamed Request: './legendary-adventurers/legendary-requests/yekaterina/yekaterina-request.md'
    - Lanavaille - Unnamed Request: './legendary-adventurers/legendary-requests/lanavaille/lanavaille-request.md'
    - Alice - Preparation of an Offering to My God: './legendary-adventurers/legendary-requests/alice/alice-request.md'
    - Gerard - Visit to My Homeland: './legendary-adventurers/legendary-requests/gerard/gerard-request.md'
    - Abenius - Accompany Me to the Old Temple in My Homeland: './legendary-adventurers/legendary-requests/abenius/abenius-request.md'
  - General Adventurers:
    - Alex: './general-adventurers/details/Alex.md'
    - Amelia: './general-adventurers/details/Amelia.md'
    - Asha: './general-adventurers/details/Asha.md'
    - Bakesh: './general-adventurers/details/Bakesh.md'
    - Barbara: './general-adventurers/details/Barbara.md'
    - Benjamin: './general-adventurers/details/Benjamin.md'
    - Bugen: './general-adventurers/details/Bugen.md'
    - Camille: './general-adventurers/details/Camille.md'
    - Chloe: './general-adventurers/details/Chloe.md'
    - Clarissa: './general-adventurers/details/Clarissa.md'
    - Daniel: './general-adventurers/details/Daniel.md'
    - Dino: './general-adventurers/details/Dino.md'
    - Eckart: './general-adventurers/details/Eckart.md'
    - Elda: './general-adventurers/details/Elda.md'
    - Eldorado: './general-adventurers/details/Eldorado.md'
    - Elise: './general-adventurers/details/Elise.md'
    - Emil: './general-adventurers/details/Emil.md'
    - Eulalia: './general-adventurers/details/Eulalia.md'
    - Flut: './general-adventurers/details/Flut.md'
    - Galina: './general-adventurers/details/Galina.md'
    - Gandolfo: './general-adventurers/details/Gandolfo.md'
    - Gaston: './general-adventurers/details/Gaston.md'
    - Heinrico: './general-adventurers/details/Heinrico.md'
    - Jarmil: './general-adventurers/details/Jarmil.md'
    - Jean: './general-adventurers/details/Jean.md'
    - Kiriha: './general-adventurers/details/Kiriha.md'
    - Marianne: './general-adventurers/details/Marianne.md'
    - Milana: './general-adventurers/details/Milana.md'
    - Olive: './general-adventurers/details/Olive.md'
    - Ophelia: './general-adventurers/details/Ophelia.md'
    - Philip: './general-adventurers/details/Philip.md'
    - Valdor: './general-adventurers/details/Valdor.md'
    - Viviana: './general-adventurers/details/Viviana.md'
  - Anonymous Adventurers:
    - Beast-Thi: './anonymous-adventurers/details/Beast-Thi.md'
    - Dwarf-Kni: './anonymous-adventurers/details/Dwarf-Kni.md'
    - Elf-Mag: './anonymous-adventurers/details/Elf-Mag.md'
    - Elf-Pri: './anonymous-adventurers/details/Elf-Pri.md'
    - Human-Fig: './anonymous-adventurers/details/Human-Fig.md'
    - Human-Nin: './anonymous-adventurers/details/Human-Nin.md'
    - Human-Pri: './anonymous-adventurers/details/Human-Pri.md'
    - Human-Sam: './anonymous-adventurers/details/Human-Sam.md'
