nav:
  - Traits and Stats: './traits-and-stats.md'
  - Discipline and Inheritance: './discipline-and-inheritance.md'
  - Merging: './merging.md'
  - Damage Mechanics: './damage-mechanics.md'
  - Skill Levels: 
    - Passives: './passive-skills.md'      
  - Map Variations: './map-variations.md'
  - Trust: 
    - Guide: './trust/trust.md'
    - Tavern and Camp Table: './trust/table.md'
  
