nav:
  - FAQ: './frequently-asked-questions.md'
  - Abyss: abyss-guides
  - Dungeons: dungeons
  - Events: events
  - Adventurers: adventurers
  - Adventurer Customization: adventurer-customization
  - Farming: farming
  - Bounties: bounties 
  - Equipment: equipment
  - Mechanics: mechanics
  - Strategies: strategies
  - Appendices: appendices
  - Tools: tools
