nav:
  - FAQ: './frequently-asked-questions.md'
  - Dungeon Guides: abyss-guides
  - Events: events
  - Adventurers: adventurers
  - Customization: adventurer-customization
  - Mechanics: mechanics
  - Equipment: equipment
  - Strategies: strategies
  - Bounties: './abyss-guides/bounties/bounties.md'
  - Appendices: appendices
  - Tools: tools
