nav:
  - FAQ: './frequently-asked-questions.md'
  - Abyss: abyss-guides
  - Dungeons and Events: events  
  - Adventurers: adventurers
  - Adventurer Customization: adventurer-customization
  - Mechanics: mechanics
  - Strategies: strategies
  - Farming: './strategies/farming.md'
  - Bounties: './abyss-guides/bounties/bounties.md' 
  - Equipment: equipment
  - Appendices: appendices
  - Tools: tools
