nav:
  - FAQ: './frequently-asked-questions.md'
  - Dungeon Guides: abyss-guides
  - Adventurers: adventurers
  - Adventurer Customization: adventurer-customization
  - Mechanics: mechanics
  - Strategies: strategies
  - Events: events
  - Appendices: appendices
  - Tools: tools