nav:
  - FAQ: './frequently-asked-questions.md'
  - Abyss Guides: abyss-guides
  - Adventurers: adventurers
  - Adventurer Customization: adventurer-customization
  - Mechanics: mechanics
  - Strategies: strategies
  - Events: events
  - Appendices: appendices
  - Tools: tools
  - Promotional Codes: './promotional-codes.md'
  - Playing on PC: './emulators/emulators.md'
  - About The Guide: './index.md'
