nav:
  - Adventurer Experience: './adventurer-experience.md'
  - Alignment: './alignment.md'
  - Bondmates:
      - Story Bondmates:
        - Bondmates Quicklist: './bondmates/bondmates-quicklist.md'
        - Bondmates Farming: './bondmates/bondmates-farming.md'
        - Beginning Abyss: './bondmates/beginning-abyss/bondmates.md'
        - Port Town Grand Legion: './bondmates/port-town-grand-legion/bondmates.md'
        - Guarda Fortress: './bondmates/guarda-fortress/bondmates.md'
        - Isberg: './bondmates/isberg/bondmates.md'
      - Trait Bondmates: './bondmates/trait-bondmates.md'
  - Class Change: './class-changes.md'
  - Contracts: './contracts.md'
  - Relicbrews: './relicbrew.md'
  - Well of the Mind: './well-of-the-mind.md'
